#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "s4g19x-stephenhillier-openshift201-may2019-tools"
def DEV_NAMESPACE = "s4g19x-stephenhillier-openshift201-may2019-dev"
def PROD_NAMESPACE = "s4g19x-stephenhillier-openshift201-may2019-prod"
def LOKI_SERVICE = "loki"

//Pipeline
node {
            stage ('Build Stage'){
                dir ('simple_pipeline') {
                    checkout scm
                    sh "oc process -f templates/loki_template.yaml -p  LOKI_SERVICE_NAME=${LOKI_SERVICE}-${BUILD_ID} | oc apply -f - -n ${DEV_NAMESPACE}"
                }
            }
    }
